### ISSUE TITLE
ERC721 Standard

### ISSUE THREAD

**Issue by dekz** [loomnetwork/cryptozombie-lessons#151]
Hey @enlight 

These lessons are absolutely awesome! 

I'd just like to talk about lesson number 5 or the one on NFT (aka ethereum/EIP#721). The implementation in cryptozombies is influenced by CryptoKitties for obvious reasons, but it is not reflective of the 721 current draft going through the EIP process. I am more than happy to work with you or someone on your team to get lesson 5 to be compliant with the proposed 721 draft. IChanges include things like no `takeOwnership` and the addition of `transferFrom` and `approvals` to be more ERC20 like.

I see your Note that this is a proposal and you're using what is in OpenZeppelin currently. OpenZeppelin are also about to change that interface to be the new proposal.

**Comment by jamesmartinduffy** [comment]
Hi @dekz, thanks for the kind words!

I looked at the EIP when writing the lesson, but it seemed like things were still being changed on a daily basis and it wasn't close enough to being a standard to base the lesson on. (E.g. A week ago the draft had tokens being referred to as "deeds", which I felt was a confusing word choice and would likely change by the final release anyway). Thus I chose to base the implementation on OpenZeppelin's contract.

I'm totally in favor of updating the lesson to be compliant with the standard, but would prefer to wait until it's an accepted standard rather than in draft form. That way we don't need to update the lesson content multiple times if it changes again before being finalized, if that makes sense.

Please feel free to keep us updated on the progress, and when it's far enough along we can update the lesson. Awesome work you guys are doing!

**Comment by dekz** [comment]
Sounds good to me, you're definitely correct, it was moving quite quickly! I'll ping you back when its moved forward with an OpenZeppelin example!

**Comment by dekz** [comment]
hey @jamesmartinduffy the NFT standard has been merged officially as [ERC721](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md). OpenZeppelin have a PR for an implementation which can be found [here](https://github.com/OpenZeppelin/zeppelin-solidity/pull/803)

**Comment by dekz** [comment]
hey @jamesmartinduffy Just checking in on this again, any updates on changing the lesson to match the interface of the ERC721? I think having it right now as the very old draft is quite misleading to new developers.

OpenZeppelin have also merged their PR as can be seen [here](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/803)

**Comment by andreipope** [comment]
hey @dekz  We are updating the lessons to match the ERC721 interface. We'll keep you updated on the progress. Thanks!

**Comment by jlubeck** [comment]
Has this been updated? Just want to make sure since I'm new to this and don't want to start off the wrong foot... thanks!
