### ISSUE TITLE
Unclear why zombieToOwner mapping is needed

### ISSUE THREAD

**Issue by schierlm** [loomnetwork/cryptozombie-lessons#189]
I've now completed the course up to level 5, and I really like it.

There is just one thing that is unclear for me: What is the rationale to having a zombieToOwner mapping instead of just adding the owner as a field to the Zombie struct? It is initialized at the same point as the others, and we are updating other fields (so the reason cannot be that they cannot be updated). Also, from other programming languages, I learned it to be a bad idea to have a mapping/hashtable whose keys are consecutive numbers (use an array instead). And since we already have an array here (the array of `Zombie` structs) I would probably have added the owner in there.

(And in case somebody complains that this should be discussed via Telegram - I refuse to sign up to any services who do not let me sign up without disclosing my mobile phone number to them, therefore I don't have a Telegram account).

**Comment by zoeleesss** [comment]
Hey. If you question is about why [cryptozombies.io](https://cryptozombies.io) use a mapping instead of adding owner as an attribute of the Zombie structure, I could explain in a way i can.

1. 
Let's say we have already added owner as an attribute. This is what might happen:

In order to query who a zombie's owner is. We just need to use:
`zombies[_tokenId].owner`. 
It seems simpler.  But truth is that every time we use:
`Zombie storage myZombie = zombies[_tokenId]` This will cost much more space because of one more parameter.
In Ethereum networks, `space+time = money`. So you don't wanna spend extra fees.

2. 
The owner attribute is better be separated because the relations between the two things.
I.E. the relation between the attributes like name, dna ,etc.. and zombie is ` 1:1 ` . But for `owner : zombie = 1 : many `.

So It makes perfect sense to make a zombieToOwner mapping.
Hope it helps you. 
If there is any error in the above explanation, please point it out. Thanks!!
Wanna contact me? `luoyexiaofeng756@gmail.com`
