### ISSUE TITLE
Lesson 6 - Chapter 7 issue

### ISSUE THREAD

**Issue by moskva** [loomnetwork/cryptozombie-lessons#288]
My code is as below:
```
        $("#txStatus").text("Eating a kitty. This may take a while...");
        return CryptoZombies.methods.feedOnKitty(zombieId, kittyId)
```
The answer shows me `KittyId` instead of `kittyId`.

        return CryptoZombies.methods.feedOnKitty(zombieId, KittyId)

![error](https://user-images.githubusercontent.com/1446952/41411423-63d5b5a2-700f-11e8-9fd6-b32a9084297e.jpg)

**Comment by Isaac12x** [comment]
I was going to post the exact same thing with a little gist to it. 

There is also an unexpected parser behaviour (or at least that's what it looked to me). In the same file (index.html) we declared cryptoZombies = new web3js.eth.Contract(cryptoZombiesABI, cryptoZombiesAddress);  but the parser needs "CryptoZombies" instead of cryptoZombies. 

Maybe is different in solidity and it's properly done - but coming from python - it's very confusing to call it as an object instead of as an object instance. 

Since we don't have access to the parser code (or I couldn't find it myself) I'm unable to open a pull request with the changes.

**Comment by andreipope** [comment]
It's fixed. I'm closing this issue.
